import type { AppSeed } from "@/lib/types";

export const seedData: AppSeed = {
  workspace: {
    id: "ws-capataz-auto-demo",
    systemMode: "automotive",
    name: "Capataz Demo | Grupo Autofin Volkswagen Puebla",
    industry: "Agencia automotriz",
    timezone: "America/Mexico_City",
    tagline: "Control comercial, post-venta e incidencias criticas para agencias y grupos automotrices.",
    scorePolicy: "Determinista, auditable y centrado en conversion, seguimiento y disciplina operativa.",
  },
  users: [
    {
      id: "usr-admin",
      name: "Ricardo Perez",
      email: "ricardo@capataz.ai",
      phone: "+5213310001001",
      password: "capataz123",
      role: "admin",
      department: "corporate",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-corporativo",
      site: "Grupo Autofin | Corporativo",
      avatar: "RP",
      accent: "#4fd1ff",
      statusLabel: "Director de marca con vista multisucursal",
    },
    {
      id: "usr-victor-demo",
      name: "Victor Ramirez",
      email: "victor@capataz.ai",
      phone: "+5213310001009",
      password: "capataz123",
      role: "owner",
      department: "general_management",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      site: "Volkswagen Puebla Centro",
      avatar: "VR",
      accent: "#ff9b71",
      statusLabel: "Dueño demo con foco en junta y cierre comercial",
    },
    {
      id: "usr-owner",
      name: "Ian Martinez",
      email: "ian@capataz.ai",
      phone: "+5213310001002",
      password: "capataz123",
      role: "owner",
      department: "general_management",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      site: "Volkswagen Puebla Centro",
      avatar: "IM",
      accent: "#9b7cff",
      statusLabel: "Gerente general de agencia",
    },
    {
      id: "usr-supervisor-1",
      name: "Laura Martinez",
      email: "laura@capataz.ai",
      phone: "+5213310001003",
      password: "capataz123",
      role: "supervisor",
      department: "sales",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      site: "Volkswagen Puebla Centro",
      avatar: "LM",
      accent: "#59f1bc",
      statusLabel: "Gerente comercial",
    },
    {
      id: "usr-supervisor-2",
      name: "Jose Luis Vega",
      email: "jose@capataz.ai",
      phone: "+5213310001004",
      password: "capataz123",
      role: "supervisor",
      department: "service",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-angelopolis",
      site: "Volkswagen Puebla Angelopolis",
      avatar: "JV",
      accent: "#ffca6b",
      statusLabel: "Gerente de servicio con incidencias abiertas",
    },
    {
      id: "usr-operator-1",
      name: "Diego Torres",
      email: "diego@capataz.ai",
      phone: "+5213310001005",
      password: "capataz123",
      role: "operator",
      department: "sales",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      site: "Volkswagen Puebla Centro",
      avatar: "DT",
      accent: "#ff7f7f",
      statusLabel: "Vendedor con pipeline bajo y post-venta vencida",
    },
    {
      id: "usr-operator-2",
      name: "Fernanda Ruiz",
      email: "fernanda@capataz.ai",
      phone: "+5213310001006",
      password: "capataz123",
      role: "operator",
      department: "sales",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-angelopolis",
      site: "Volkswagen Puebla Angelopolis",
      avatar: "FR",
      accent: "#7be495",
      statusLabel: "Vendedora consistente en pruebas de manejo",
    },
    {
      id: "usr-operator-3",
      name: "Ana Belen Soto",
      email: "ana@capataz.ai",
      phone: "+5213310001007",
      password: "capataz123",
      role: "operator",
      department: "service",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      site: "Volkswagen Puebla Centro",
      avatar: "AS",
      accent: "#8bc8ff",
      statusLabel: "Asesora de servicio con reportes diarios al corriente",
    },
    {
      id: "usr-operator-4",
      name: "Carlos Medina",
      email: "carlos@capataz.ai",
      phone: "+5213310001008",
      password: "capataz123",
      role: "operator",
      department: "parts",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      site: "Volkswagen Puebla Centro",
      avatar: "CM",
      accent: "#c38bff",
      statusLabel: "Encargado de refacciones y campana de clientes",
    },
  ],
  columns: [
    { id: "pending", title: "Pendiente", color: "#7dc6ff", limit: 8 },
    { id: "in_progress", title: "En proceso", color: "#7ef0c7", limit: 6 },
    { id: "blocked", title: "Bloqueada", color: "#ffb86b", limit: 4 },
    { id: "done", title: "Completada", color: "#cf7bff", limit: 12 },
  ],
  tasks: [
    {
      id: "tsk-1",
      title: "Preparar junta diaria de pendientes comerciales",
      description: "Consolidar pruebas de manejo, apartados, expedientes incompletos y cierres probables antes de la junta de las 8:30.",
      priority: "critical",
      columnId: "pending",
      assigneeId: "usr-supervisor-1",
      reporterId: "usr-owner",
      dueAt: "2026-03-13T14:30:00.000Z",
      createdAt: "2026-03-12T16:00:00.000Z",
      updatedAt: "2026-03-12T18:00:00.000Z",
      location: "Sala de juntas comercial",
      tags: ["junta", "ventas", "pipeline"],
      requiresChecklist: true,
      checklistInstanceId: "chk-1",
    },
    {
      id: "tsk-2",
      title: "Registrar guardia y clientes nuevos del piso",
      description: "Cargar en Capataz los prospectos captados en guardia y agendar seguimiento inicial.",
      priority: "medium",
      columnId: "in_progress",
      assigneeId: "usr-operator-2",
      reporterId: "usr-supervisor-1",
      dueAt: "2026-03-13T17:00:00.000Z",
      createdAt: "2026-03-12T13:40:00.000Z",
      updatedAt: "2026-03-12T17:20:00.000Z",
      location: "Piso de ventas",
      tags: ["guardia", "prospectos"],
      requiresChecklist: false,
    },
    {
      id: "tsk-3",
      title: "Cerrar avalúo de usado para toma a cuenta",
      description: "La operación sigue bloqueada hasta recibir diagnóstico y propuesta autorizada para la unidad usada.",
      priority: "critical",
      columnId: "blocked",
      assigneeId: "usr-supervisor-2",
      reporterId: "usr-admin",
      dueAt: "2026-03-13T15:45:00.000Z",
      createdAt: "2026-03-11T20:10:00.000Z",
      updatedAt: "2026-03-12T19:10:00.000Z",
      location: "Patio seminuevos",
      tags: ["avaluo", "usado", "bloqueo"],
      requiresChecklist: true,
      checklistInstanceId: "chk-2",
      blockedReason: "Diagnóstico mecánico y precio final pendientes",
    },
    {
      id: "tsk-4",
      title: "Seguimiento post-venta a entregas de la semana",
      description: "Contactar a clientes entregados en la semana para evitar fuga a otra agencia y registrar resultado.",
      priority: "high",
      columnId: "pending",
      assigneeId: "usr-operator-1",
      reporterId: "usr-supervisor-1",
      dueAt: "2026-03-13T19:00:00.000Z",
      createdAt: "2026-03-12T15:00:00.000Z",
      updatedAt: "2026-03-12T15:00:00.000Z",
      location: "CRM Post-venta",
      tags: ["postventa", "retencion"],
      requiresChecklist: true,
      checklistInstanceId: "chk-3",
    },
    {
      id: "tsk-5",
      title: "Levantar incidente de campana por cliente molesto",
      description: "Documentar caso, gerente que atendió, causa y siguiente paso para cierre del incidente.",
      priority: "critical",
      columnId: "pending",
      assigneeId: "usr-operator-4",
      reporterId: "usr-owner",
      dueAt: "2026-03-13T13:30:00.000Z",
      createdAt: "2026-03-12T11:20:00.000Z",
      updatedAt: "2026-03-12T11:20:00.000Z",
      location: "Sala de ventas",
      tags: ["campana", "cliente", "incidente"],
      requiresChecklist: false,
    },
    {
      id: "tsk-6",
      title: "Expediente de crédito completo para Jetta Comfortline",
      description: "Solicitud cerrada con comprobantes, estados de cuenta y validación de financiera de la marca.",
      priority: "high",
      columnId: "done",
      assigneeId: "usr-operator-2",
      reporterId: "usr-supervisor-1",
      dueAt: "2026-03-12T18:30:00.000Z",
      createdAt: "2026-03-11T10:10:00.000Z",
      updatedAt: "2026-03-12T18:15:00.000Z",
      completedAt: "2026-03-12T18:15:00.000Z",
      location: "Financiamiento VWFS",
      tags: ["credito", "expediente", "vwfs"],
      requiresChecklist: true,
      checklistInstanceId: "chk-4",
    },
    {
      id: "tsk-7",
      title: "Revisar subvención aplicada al enganche",
      description: "Validar que la subvención se haya ofrecido conforme a política y que no quede oculta para inflar comisión.",
      priority: "high",
      columnId: "in_progress",
      assigneeId: "usr-supervisor-1",
      reporterId: "usr-admin",
      dueAt: "2026-03-13T20:00:00.000Z",
      createdAt: "2026-03-12T09:30:00.000Z",
      updatedAt: "2026-03-12T19:50:00.000Z",
      location: "Oficina comercial",
      tags: ["subvencion", "comision", "auditoria"],
      requiresChecklist: false,
    },
    {
      id: "tsk-8",
      title: "Registrar convocatoria del himno matutino",
      description: "Dejar listo el broadcast diario de las 8:00 a.m. con convocatoria y audio institucional.",
      priority: "medium",
      columnId: "done",
      assigneeId: "usr-owner",
      reporterId: "usr-admin",
      dueAt: "2026-03-12T14:00:00.000Z",
      createdAt: "2026-03-11T22:30:00.000Z",
      updatedAt: "2026-03-12T08:45:00.000Z",
      completedAt: "2026-03-12T08:45:00.000Z",
      location: "Comunicacion interna",
      tags: ["broadcast", "himno"],
      requiresChecklist: false,
    },
  ],
  checklists: [
    {
      id: "chk-1",
      taskId: "tsk-1",
      templateName: "Junta diaria comercial",
      assigneeId: "usr-supervisor-1",
      status: "in_progress",
      items: [
        { id: "chk-1-1", label: "Consolidar pruebas de manejo del dia anterior", done: true, required: true, completedAt: "2026-03-12T18:05:00.000Z" },
        { id: "chk-1-2", label: "Listar expedientes de credito incompletos", done: false, required: true },
        { id: "chk-1-3", label: "Identificar cierres probables de fin de mes", done: false, required: true },
      ],
    },
    {
      id: "chk-2",
      taskId: "tsk-3",
      templateName: "Toma de usado a cuenta",
      assigneeId: "usr-supervisor-2",
      status: "pending",
      items: [
        { id: "chk-2-1", label: "Diagnóstico mecánico recibido", done: false, required: true },
        { id: "chk-2-2", label: "Avalúo comercial capturado", done: true, required: true, completedAt: "2026-03-12T16:40:00.000Z" },
        { id: "chk-2-3", label: "Oferta final negociada con cliente", done: false, required: true },
      ],
    },
    {
      id: "chk-3",
      taskId: "tsk-4",
      templateName: "Seguimiento post-venta inicial",
      assigneeId: "usr-operator-1",
      status: "pending",
      items: [
        { id: "chk-3-1", label: "Llamada de post-entrega realizada", done: false, required: true },
        { id: "chk-3-2", label: "Resultado capturado en CRM", done: false, required: true },
        { id: "chk-3-3", label: "Próximo contacto calendarizado", done: false, required: true },
      ],
    },
    {
      id: "chk-4",
      taskId: "tsk-6",
      templateName: "Expediente de crédito VWFS",
      assigneeId: "usr-operator-2",
      status: "complete",
      items: [
        { id: "chk-4-1", label: "Solicitud firmada", done: true, required: true, completedAt: "2026-03-12T17:55:00.000Z" },
        { id: "chk-4-2", label: "Comprobantes y estados cargados", done: true, required: true, completedAt: "2026-03-12T18:05:00.000Z" },
        { id: "chk-4-3", label: "Validacion de financiera completada", done: true, required: true, completedAt: "2026-03-12T18:10:00.000Z" },
      ],
    },
  ],
  alerts: [
    {
      id: "alt-1",
      title: "Avalúo usado sigue bloqueado",
      body: "La toma a cuenta no puede avanzar hasta recibir diagnóstico y precio final autorizado.",
      severity: "critical",
      read: false,
      createdAt: "2026-03-12T19:15:00.000Z",
      relatedTaskId: "tsk-3",
    },
    {
      id: "alt-2",
      title: "Diego no ha hecho seguimiento post-venta",
      body: "Hay entregas de la semana sin llamada registrada y eso pone en riesgo recompra.",
      severity: "warning",
      read: false,
      createdAt: "2026-03-12T20:00:00.000Z",
      relatedTaskId: "tsk-4",
    },
    {
      id: "alt-3",
      title: "Expediente VWFS validado",
      body: "La operación del Jetta Comfortline quedó lista para paso con financiera de marca.",
      severity: "info",
      read: true,
      createdAt: "2026-03-12T18:20:00.000Z",
      relatedTaskId: "tsk-6",
    },
  ],
  activity: [
    { id: "act-1", actorId: "usr-supervisor-1", message: "Consolido los pendientes para la junta diaria comercial", createdAt: "2026-03-12T16:05:00.000Z" },
    { id: "act-2", actorId: "usr-operator-2", message: "Completo expediente de credito para Jetta Comfortline con VWFS", createdAt: "2026-03-12T18:15:00.000Z" },
    { id: "act-3", actorId: "usr-admin", message: "Marco el avalúo usado como bloqueado por falta de diagnóstico final", createdAt: "2026-03-12T19:15:00.000Z" },
    { id: "act-4", actorId: "usr-owner", message: "Reviso conversion por vendedor y cierre probable de fin de mes", createdAt: "2026-03-12T21:00:00.000Z" },
  ],
  prospects: [
    {
      id: "prs-1",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      customerName: "Mario Cazares",
      salespersonId: "usr-operator-1",
      agency: "Volkswagen Puebla Centro",
      source: "Guardia piso",
      status: "follow_up",
      createdAt: "2026-03-12T17:00:00.000Z",
      nextActionAt: "2026-03-13T16:00:00.000Z",
      vehicleInterest: "Taos Highline",
      financingRequired: true,
      notes: "Trae enganche listo, falta validacion de descuento y prueba de manejo.",
    },
    {
      id: "prs-2",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-angelopolis",
      customerName: "Karla Nuñez",
      salespersonId: "usr-operator-2",
      agency: "Volkswagen Puebla Angelopolis",
      source: "Facebook Lead",
      status: "test_drive",
      createdAt: "2026-03-12T12:30:00.000Z",
      nextActionAt: "2026-03-13T18:30:00.000Z",
      vehicleInterest: "Jetta Comfortline",
      financingRequired: true,
      notes: "Confirmo visita con pareja, alta probabilidad de cierre.",
    },
    {
      id: "prs-3",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      customerName: "Luis Ortega",
      salespersonId: "usr-operator-1",
      agency: "Volkswagen Puebla Centro",
      source: "Referido",
      status: "negotiation",
      createdAt: "2026-03-11T20:00:00.000Z",
      nextActionAt: "2026-03-13T14:00:00.000Z",
      vehicleInterest: "Tiguan R-Line",
      financingRequired: false,
      notes: "Evalua usado a cuenta. Pendiente avalúo final.",
    },
    {
      id: "prs-4",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      customerName: "Patricia Ramos",
      salespersonId: "usr-operator-3",
      agency: "Volkswagen Puebla Centro",
      source: "Servicio recurrente",
      status: "closed_won",
      createdAt: "2026-03-10T15:00:00.000Z",
      vehicleInterest: "Servicio mayor 45,000 km",
      financingRequired: false,
      notes: "Cliente satisfecha, candidata a recompra en proximo ciclo.",
    },
  ],
  testDrives: [
    {
      id: "td-1",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      prospectId: "prs-1",
      salespersonId: "usr-operator-1",
      agency: "Volkswagen Puebla Centro",
      vehicleModel: "Taos Highline",
      scheduledAt: "2026-03-13T18:00:00.000Z",
      status: "scheduled",
    },
    {
      id: "td-2",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-angelopolis",
      prospectId: "prs-2",
      salespersonId: "usr-operator-2",
      agency: "Volkswagen Puebla Angelopolis",
      vehicleModel: "Jetta Comfortline",
      scheduledAt: "2026-03-13T17:00:00.000Z",
      status: "scheduled",
    },
    {
      id: "td-3",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      prospectId: "prs-3",
      salespersonId: "usr-operator-1",
      agency: "Volkswagen Puebla Centro",
      vehicleModel: "Tiguan R-Line",
      scheduledAt: "2026-03-12T19:00:00.000Z",
      status: "completed",
      completedAt: "2026-03-12T19:45:00.000Z",
    },
  ],
  salesOperations: [
    {
      id: "op-1",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      prospectId: "prs-1",
      customerName: "Mario Cazares",
      agency: "Volkswagen Puebla Centro",
      salespersonId: "usr-operator-1",
      vehicleModel: "Taos Highline",
      stage: "negotiation",
      source: "Guardia piso",
      financingRequired: true,
      financier: "VWFS",
      subsidyType: "down_payment",
      subsidyAmount: 18000,
      tradeInRequired: false,
      closingProbability: 72,
      expectedCloseAt: "2026-03-18T19:00:00.000Z",
      nextStep: "Cerrar descuento y expediente de credito antes del lunes.",
      notes: "Cliente trae enganche listo. Riesgo moderado por aprobacion de descuento.",
      createdAt: "2026-03-12T17:10:00.000Z",
      updatedAt: "2026-03-12T19:20:00.000Z",
    },
    {
      id: "op-2",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-angelopolis",
      prospectId: "prs-2",
      customerName: "Karla Nuñez",
      agency: "Volkswagen Puebla Angelopolis",
      salespersonId: "usr-operator-2",
      vehicleModel: "Jetta Comfortline",
      stage: "credit_review",
      source: "Facebook Lead",
      financingRequired: true,
      financier: "VWFS",
      subsidyType: "rate",
      subsidyAmount: 9500,
      tradeInRequired: false,
      closingProbability: 84,
      expectedCloseAt: "2026-03-16T18:00:00.000Z",
      nextStep: "Mandar expediente completo y confirmar firma.",
      notes: "Operacion sana; solo falta respuesta formal de financiera.",
      createdAt: "2026-03-12T13:10:00.000Z",
      updatedAt: "2026-03-12T18:40:00.000Z",
    },
    {
      id: "op-3",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      prospectId: "prs-3",
      customerName: "Luis Ortega",
      agency: "Volkswagen Puebla Centro",
      salespersonId: "usr-operator-1",
      vehicleModel: "Tiguan R-Line",
      stage: "ready_to_close",
      source: "Referido",
      financingRequired: false,
      financier: "Contado",
      subsidyType: "none",
      subsidyAmount: 0,
      tradeInRequired: true,
      closingProbability: 90,
      expectedCloseAt: "2026-03-14T17:00:00.000Z",
      nextStep: "Cerrar toma a cuenta y firmar pedido.",
      notes: "La prueba de manejo ya se hizo; depende de avalúo final del usado.",
      createdAt: "2026-03-11T20:10:00.000Z",
      updatedAt: "2026-03-12T19:30:00.000Z",
    },
    {
      id: "op-4",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      prospectId: "prs-4",
      customerName: "Patricia Ramos",
      agency: "Volkswagen Puebla Centro",
      salespersonId: "usr-operator-3",
      vehicleModel: "Servicio mayor 45,000 km",
      stage: "closed_won",
      source: "Servicio recurrente",
      financingRequired: false,
      financier: "Contado",
      subsidyType: "none",
      subsidyAmount: 0,
      tradeInRequired: false,
      closingProbability: 100,
      expectedCloseAt: "2026-03-10T17:00:00.000Z",
      nextStep: "Mantener contacto para recompra y programa de servicio.",
      notes: "Caso ganado y candidato fuerte a recompra.",
      createdAt: "2026-03-10T15:00:00.000Z",
      updatedAt: "2026-03-10T18:20:00.000Z",
      closedAt: "2026-03-10T18:20:00.000Z",
    },
  ],
  creditFiles: [
    {
      id: "cf-1",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      operationId: "op-1",
      customerName: "Mario Cazares",
      agency: "Volkswagen Puebla Centro",
      salespersonId: "usr-operator-1",
      financier: "VWFS",
      status: "missing_documents",
      downPaymentReady: true,
      requiredDocuments: ["Solicitud firmada", "INE", "Comprobante de domicilio", "Estados de cuenta"],
      receivedDocuments: ["Solicitud firmada", "INE"],
      missingDocuments: ["Comprobante de domicilio", "Estados de cuenta"],
      notes: "Falta cerrar expediente para no enfriar la operacion.",
    },
    {
      id: "cf-2",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-angelopolis",
      operationId: "op-2",
      customerName: "Karla Nuñez",
      agency: "Volkswagen Puebla Angelopolis",
      salespersonId: "usr-operator-2",
      financier: "VWFS",
      status: "submitted",
      downPaymentReady: true,
      requiredDocuments: ["Solicitud firmada", "INE", "Comprobante de domicilio", "Estados de cuenta"],
      receivedDocuments: ["Solicitud firmada", "INE", "Comprobante de domicilio", "Estados de cuenta"],
      missingDocuments: [],
      submittedAt: "2026-03-12T18:15:00.000Z",
      notes: "Esperando dictamen final de financiera.",
    },
  ],
  bellIncidents: [
    {
      id: "inc-1",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      customerName: "Hector Mendoza",
      agency: "Volkswagen Puebla Centro",
      area: "sales",
      severity: "critical",
      status: "open",
      summary: "Cliente toco campana por demora en entrega y mala explicacion del descuento.",
      ownerId: "usr-owner",
      createdAt: "2026-03-13T13:10:00.000Z",
      updatedAt: "2026-03-13T13:10:00.000Z",
    },
    {
      id: "inc-2",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-angelopolis",
      customerName: "Rocio Bernal",
      agency: "Volkswagen Puebla Angelopolis",
      area: "service",
      severity: "warning",
      status: "in_progress",
      summary: "Molestia por atraso en entrega de unidad de servicio y falta de llamada previa.",
      ownerId: "usr-supervisor-2",
      createdAt: "2026-03-12T16:20:00.000Z",
      updatedAt: "2026-03-12T17:00:00.000Z",
    },
  ],
  postSaleFollowUps: [
    {
      id: "psf-1",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-centro",
      customerName: "Mario Cazares",
      vehicleModel: "Virtus Comfortline",
      salespersonId: "usr-operator-1",
      agency: "Volkswagen Puebla Centro",
      saleDate: "2026-03-05T18:00:00.000Z",
      dueAt: "2026-03-13T17:30:00.000Z",
      status: "at_risk",
      nextStep: "Llamar hoy para evitar fuga a otra agencia y documentar satisfaccion.",
    },
    {
      id: "psf-2",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-angelopolis",
      customerName: "Patricia Ramos",
      vehicleModel: "Jetta Sportline",
      salespersonId: "usr-operator-2",
      agency: "Volkswagen Puebla Angelopolis",
      saleDate: "2026-03-08T19:00:00.000Z",
      dueAt: "2026-03-13T18:00:00.000Z",
      status: "pending",
      nextStep: "Enviar mensaje de seguimiento y agendar primer servicio.",
    },
    {
      id: "psf-3",
      groupId: "grp-autofin",
      brandId: "brand-vw",
      siteId: "site-vw-puebla-angelopolis",
      customerName: "Daniela Flores",
      vehicleModel: "Taigun Trendline",
      salespersonId: "usr-operator-2",
      agency: "Volkswagen Puebla Angelopolis",
      saleDate: "2026-03-03T18:30:00.000Z",
      dueAt: "2026-03-10T18:30:00.000Z",
      status: "contacted",
      nextStep: "Dar seguimiento en 30 dias para accesorios y referidos.",
      lastContactAt: "2026-03-11T17:00:00.000Z",
    },
  ],
  scheduledBroadcasts: [
    {
      id: "brd-1",
      title: "Convocatoria himno matutino",
      message: "Capataz.ai: son las 8:00 a.m. Favor de reunirse en patio principal para himno y arranque operativo.",
      audioLabel: "himno-capataz-v1.mp3",
      audience: "all_staff",
      frequency: "daily",
      timeOfDay: "08:00",
      timezone: "America/Mexico_City",
      active: true,
    },
    {
      id: "brd-2",
      title: "Corte comercial vespertino",
      message: "Capataz.ai: favor de mandar cierre comercial, pruebas de manejo y operaciones listas antes de las 5:45 p.m.",
      audience: "sales_only",
      frequency: "weekdays",
      timeOfDay: "17:45",
      timezone: "America/Mexico_City",
      active: true,
    },
  ],
  scoreSnapshots: [
    { userId: "usr-supervisor-1", compliance: 93, speed: 88, consistency: 91, activity: 90, score: 91, trend: "up", note: "Mantiene juntas diarias claras y presiona cierres con buena disciplina." },
    { userId: "usr-operator-1", compliance: 60, speed: 64, consistency: 58, activity: 62, score: 61, trend: "down", note: "Trae seguimiento post-venta atrasado y pocas pruebas de manejo recientes." },
    { userId: "usr-operator-2", compliance: 89, speed: 84, consistency: 87, activity: 82, score: 86, trend: "up", note: "Buen ritmo en prospectos, pruebas y expedientes de credito." },
    { userId: "usr-supervisor-2", compliance: 73, speed: 68, consistency: 72, activity: 70, score: 71, trend: "steady", note: "Riesgo moderado por operaciones atoradas en usados y servicio." },
    { userId: "usr-operator-3", compliance: 87, speed: 82, consistency: 88, activity: 84, score: 85, trend: "up", note: "Documenta bien reportes de servicio y mantiene seguimiento constante." },
    { userId: "usr-operator-4", compliance: 80, speed: 75, consistency: 79, activity: 77, score: 78, trend: "steady", note: "Buen soporte en refacciones y atencion inicial de incidentes." },
  ],
  weekly: [
    { day: "Lun", completed: 7, alerts: 2, overdue: 1 },
    { day: "Mar", completed: 9, alerts: 1, overdue: 1 },
    { day: "Mie", completed: 6, alerts: 3, overdue: 2 },
    { day: "Jue", completed: 10, alerts: 2, overdue: 1 },
    { day: "Vie", completed: 8, alerts: 3, overdue: 2 },
    { day: "Sab", completed: 5, alerts: 1, overdue: 1 },
    { day: "Dom", completed: 4, alerts: 1, overdue: 0 },
  ],
  financeAccounts: [
    { id: "fa-1", userId: "usr-operator-1", kind: "wallet", label: "Saldo disponible", currency: "MXN", availableBalance: 3820, pendingBalance: 450, updatedAt: "2026-03-18T10:05:00.000Z" },
    { id: "fa-2", userId: "usr-operator-1", kind: "credit_line", label: "Linea activa", currency: "MXN", availableBalance: 0, pendingBalance: 0, creditLimit: 8000, updatedAt: "2026-03-18T10:05:00.000Z" },
    { id: "fa-3", userId: "usr-operator-2", kind: "wallet", label: "Saldo disponible", currency: "MXN", availableBalance: 6170, pendingBalance: 0, updatedAt: "2026-03-18T10:05:00.000Z" },
    { id: "fa-4", userId: "usr-operator-2", kind: "benefits", label: "Bolsa de beneficios", currency: "MXN", availableBalance: 2400, pendingBalance: 0, updatedAt: "2026-03-18T10:05:00.000Z" },
    { id: "fa-5", userId: "usr-operator-3", kind: "wallet", label: "Saldo disponible", currency: "MXN", availableBalance: 5940, pendingBalance: 0, updatedAt: "2026-03-18T10:05:00.000Z" },
    { id: "fa-6", userId: "usr-operator-4", kind: "wallet", label: "Saldo disponible", currency: "MXN", availableBalance: 4510, pendingBalance: 320, updatedAt: "2026-03-18T10:05:00.000Z" },
    { id: "fa-7", userId: "usr-supervisor-1", kind: "wallet", label: "Saldo disponible", currency: "MXN", availableBalance: 11380, pendingBalance: 0, updatedAt: "2026-03-18T10:05:00.000Z" },
  ],
  financeMovements: [
    { id: "fm-1", userId: "usr-operator-1", accountId: "fa-1", type: "payroll", status: "posted", title: "Nomina quincenal", detail: "Deposito de nomina", amount: 7250, createdAt: "2026-03-15T08:10:00.000Z" },
    { id: "fm-2", userId: "usr-operator-1", accountId: "fa-1", type: "payment", status: "posted", title: "Pago microcredito", detail: "Cobro automatico del periodo", amount: -833, createdAt: "2026-03-16T09:00:00.000Z" },
    { id: "fm-3", userId: "usr-operator-1", accountId: "fa-1", type: "bonus", status: "posted", title: "Bono por cierre", detail: "Incentivo por meta semanal", amount: 1100, createdAt: "2026-03-17T12:40:00.000Z" },
    { id: "fm-4", userId: "usr-operator-1", accountId: "fa-1", type: "reserve", status: "pending", title: "Reserva de adelanto", detail: "Retencion por solicitud enviada", amount: -450, createdAt: "2026-03-18T08:20:00.000Z" },
    { id: "fm-5", userId: "usr-operator-2", accountId: "fa-3", type: "payroll", status: "posted", title: "Nomina quincenal", detail: "Deposito de nomina", amount: 7600, createdAt: "2026-03-15T08:10:00.000Z" },
    { id: "fm-6", userId: "usr-operator-2", accountId: "fa-3", type: "cashback", status: "posted", title: "Cashback por score", detail: "Beneficio por score arriba de 80", amount: 320, createdAt: "2026-03-16T10:00:00.000Z" },
    { id: "fm-7", userId: "usr-operator-2", accountId: "fa-4", type: "bonus", status: "posted", title: "Bolsa de movilidad", detail: "Apoyo mensual de gasolina", amount: 900, createdAt: "2026-03-17T11:20:00.000Z" },
    { id: "fm-8", userId: "usr-operator-2", accountId: "fa-3", type: "purchase", status: "posted", title: "Pago de celular", detail: "Compra ligada a credito de herramientas", amount: -1280, createdAt: "2026-03-18T09:15:00.000Z" },
    { id: "fm-9", userId: "usr-operator-3", accountId: "fa-5", type: "payroll", status: "posted", title: "Nomina quincenal", detail: "Deposito de nomina", amount: 7350, createdAt: "2026-03-15T08:10:00.000Z" },
    { id: "fm-10", userId: "usr-operator-3", accountId: "fa-5", type: "bonus", status: "posted", title: "Bono experiencia cliente", detail: "Servicio y post-venta destacados", amount: 850, createdAt: "2026-03-17T16:00:00.000Z" },
    { id: "fm-11", userId: "usr-operator-4", accountId: "fa-6", type: "payroll", status: "posted", title: "Nomina quincenal", detail: "Deposito de nomina", amount: 7080, createdAt: "2026-03-15T08:10:00.000Z" },
    { id: "fm-12", userId: "usr-operator-4", accountId: "fa-6", type: "payment", status: "posted", title: "Pago seguro operativo", detail: "Cobertura mensual", amount: -89, createdAt: "2026-03-17T08:30:00.000Z" },
    { id: "fm-13", userId: "usr-supervisor-1", accountId: "fa-7", type: "payroll", status: "posted", title: "Nomina quincenal", detail: "Deposito de nomina", amount: 12800, createdAt: "2026-03-15T08:10:00.000Z" },
    { id: "fm-14", userId: "usr-supervisor-1", accountId: "fa-7", type: "cashback", status: "posted", title: "Cashback por cumplimiento", detail: "Programa Capataz Capital", amount: 650, createdAt: "2026-03-17T09:40:00.000Z" },
    { id: "fm-15", userId: "usr-supervisor-1", accountId: "fa-7", type: "reserve", status: "scheduled", title: "Reserva seguro del equipo", detail: "Cargo programado de beneficios", amount: -420, createdAt: "2026-03-20T08:00:00.000Z" },
  ],
  financeApplications: [
    {
      id: "fapp-1",
      userId: "usr-operator-1",
      productId: "micro_credit",
      productName: "Microcredito personal",
      requestedAmount: 5000,
      status: "disbursed",
      requestedAt: "2026-02-01T11:00:00.000Z",
      updatedAt: "2026-02-02T16:20:00.000Z",
      paymentPerPeriod: 833,
      termLabel: "6 meses",
      rationale: "Gasto medico familiar",
      aiSummary: "El score y la actividad sostenida permitieron desembolso rapido.",
    },
    {
      id: "fapp-2",
      userId: "usr-operator-1",
      productId: "salary_advance",
      productName: "Adelanto de nomina",
      requestedAmount: 2500,
      status: "under_review",
      requestedAt: "2026-03-18T08:15:00.000Z",
      updatedAt: "2026-03-18T09:00:00.000Z",
      paymentPerPeriod: 2500,
      termLabel: "Quincena",
      rationale: "Cubrir traslado y documentacion de cliente prioritario",
      aiSummary: "Hay score suficiente, pero conviene cerrar dos tareas vencidas antes de ampliar linea.",
    },
    {
      id: "fapp-3",
      userId: "usr-operator-2",
      productId: "tooling_credit",
      productName: "Credito herramientas",
      requestedAmount: 12000,
      status: "approved",
      requestedAt: "2026-03-14T14:20:00.000Z",
      updatedAt: "2026-03-17T10:30:00.000Z",
      paymentPerPeriod: 1200,
      termLabel: "10 meses",
      rationale: "Renovar smartphone y laptop de trabajo",
      aiSummary: "Aprobacion recomendada por score alto, buen ritmo de cierre y bajo riesgo operativo.",
    },
    {
      id: "fapp-4",
      userId: "usr-operator-4",
      productId: "shield_plus",
      productName: "Seguro operativo",
      requestedAmount: 0,
      status: "approved",
      requestedAt: "2026-03-10T10:10:00.000Z",
      updatedAt: "2026-03-10T10:40:00.000Z",
      paymentPerPeriod: 89,
      termLabel: "Mensual",
      rationale: "Cobertura de trabajo y asistencia",
      aiSummary: "Producto base aprobado en automatico por politica de beneficios.",
    },
  ],
  financeInsights: [
    { id: "fi-1", userId: "usr-operator-1", title: "Score util, caja apretada", body: "Diego puede acceder a adelanto de nomina, pero el sistema detecta friccion por tareas vencidas y seguimiento post-venta en riesgo.", tone: "warning", createdAt: "2026-03-18T09:05:00.000Z" },
    { id: "fi-2", userId: "usr-operator-2", title: "Talento premium para credito", body: "Fernanda mantiene score alto y pipeline sano; Capataz recomienda usarla como caso ejemplar en la demo de fintech laboral.", tone: "positive", createdAt: "2026-03-18T09:10:00.000Z" },
    { id: "fi-3", title: "Bolsa financiera del grupo", body: "La cartera activa del piloto sigue sana: dos solicitudes aprobadas, una dispersada y una en revision por riesgo operativo moderado.", tone: "positive", createdAt: "2026-03-18T09:20:00.000Z" },
    { id: "fi-4", title: "Riesgo de sobreendeudamiento bajo", body: "Ningun colaborador visible rebasa umbral rojo. La alerta relevante hoy es calidad operativa, no mora.", tone: "positive", createdAt: "2026-03-18T09:25:00.000Z" },
  ],
};
