import type { AppSeed } from "@/lib/types";

export const hospitalSeedData: AppSeed = {
  workspace: {
    id: "ws-capataz-hospital-demo",
    systemMode: "hospital",
    name: "Capataz Hospital Demo | Red Santa Emilia",
    industry: "Hospital privado",
    timezone: "America/Mexico_City",
    tagline: "Operacion clinica, admisiones, egresos e incidentes criticos en una sola consola.",
    scorePolicy: "Determinista, auditable y centrado en tiempos de respuesta, continuidad de cuidado y disciplina operativa.",
  },
  users: [
    {
      id: "h-usr-admin",
      name: "Ricardo Perez",
      email: "ricardo.hospital@capataz.ai",
      phone: "+5213310002001",
      password: "capataz123",
      role: "admin",
      department: "corporate",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-corporativo",
      site: "Red Santa Emilia | Corporativo",
      avatar: "RP",
      accent: "#4fd1ff",
      statusLabel: "Director corporativo con vista multisede",
    },
    {
      id: "h-usr-owner",
      name: "Mariana Solis",
      email: "mariana.hospital@capataz.ai",
      phone: "+5213310002002",
      password: "capataz123",
      role: "owner",
      department: "general_management",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      site: "Hospital Santa Emilia Central",
      avatar: "MS",
      accent: "#ff9b71",
      statusLabel: "Direccion general con foco en camas, admisiones y incidentes",
    },
    {
      id: "h-usr-supervisor-1",
      name: "Laura Martinez",
      email: "laura.hospital@capataz.ai",
      phone: "+5213310002003",
      password: "capataz123",
      role: "supervisor",
      department: "sales",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      site: "Hospital Santa Emilia Central",
      avatar: "LM",
      accent: "#59f1bc",
      statusLabel: "Gerente de admisiones y coordinacion hospitalaria",
    },
    {
      id: "h-usr-supervisor-2",
      name: "Jose Vega",
      email: "jose.hospital@capataz.ai",
      phone: "+5213310002004",
      password: "capataz123",
      role: "supervisor",
      department: "service",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-norte",
      site: "Hospital Santa Emilia Norte",
      avatar: "JV",
      accent: "#ffca6b",
      statusLabel: "Coordinador de enfermeria con incidentes por resolver",
    },
    {
      id: "h-usr-operator-1",
      name: "Diego Torres",
      email: "diego.hospital@capataz.ai",
      phone: "+5213310002005",
      password: "capataz123",
      role: "operator",
      department: "sales",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      site: "Hospital Santa Emilia Central",
      avatar: "DT",
      accent: "#ff7f7f",
      statusLabel: "Ejecutivo de admisiones con varios ingresos por confirmar",
    },
    {
      id: "h-usr-operator-2",
      name: "Fernanda Ruiz",
      email: "fernanda.hospital@capataz.ai",
      phone: "+5213310002006",
      password: "capataz123",
      role: "operator",
      department: "sales",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-norte",
      site: "Hospital Santa Emilia Norte",
      avatar: "FR",
      accent: "#7be495",
      statusLabel: "Coordinadora de seguros y programacion de estudios",
    },
    {
      id: "h-usr-operator-3",
      name: "Ana Soto",
      email: "ana.hospital@capataz.ai",
      phone: "+5213310002007",
      password: "capataz123",
      role: "operator",
      department: "service",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      site: "Hospital Santa Emilia Central",
      avatar: "AS",
      accent: "#8bc8ff",
      statusLabel: "Enfermeria de piso con egresos y seguimiento al alta",
    },
    {
      id: "h-usr-operator-4",
      name: "Carlos Medina",
      email: "carlos.hospital@capataz.ai",
      phone: "+5213310002008",
      password: "capataz123",
      role: "operator",
      department: "admin",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      site: "Hospital Santa Emilia Central",
      avatar: "CM",
      accent: "#c38bff",
      statusLabel: "Mesa administrativa y autorizaciones con aseguradoras",
    },
  ],
  columns: [
    { id: "pending", title: "Pendiente", color: "#7dc6ff", limit: 10 },
    { id: "in_progress", title: "En proceso", color: "#7ef0c7", limit: 8 },
    { id: "blocked", title: "Bloqueada", color: "#ffb86b", limit: 5 },
    { id: "done", title: "Completada", color: "#cf7bff", limit: 16 },
  ],
  tasks: [
    {
      id: "h-tsk-1",
      title: "Preparar junta de admisiones y ocupacion",
      description: "Consolidar ingresos programados, camas disponibles, egresos y autorizaciones pendientes antes de la junta de las 7:15.",
      priority: "critical",
      columnId: "pending",
      assigneeId: "h-usr-supervisor-1",
      reporterId: "h-usr-owner",
      dueAt: "2026-03-16T13:15:00.000Z",
      createdAt: "2026-03-15T14:00:00.000Z",
      updatedAt: "2026-03-15T18:10:00.000Z",
      location: "Sala de comando clinico",
      tags: ["junta", "admisiones", "camas"],
      requiresChecklist: true,
      checklistInstanceId: "h-chk-1",
    },
    {
      id: "h-tsk-2",
      title: "Confirmar autorizacion de aseguradora para laparoscopia",
      description: "El ingreso no puede moverse a quirofano hasta recibir folio de autorizacion y validar habitacion.",
      priority: "critical",
      columnId: "blocked",
      assigneeId: "h-usr-operator-4",
      reporterId: "h-usr-supervisor-1",
      dueAt: "2026-03-16T15:00:00.000Z",
      createdAt: "2026-03-15T16:10:00.000Z",
      updatedAt: "2026-03-15T19:20:00.000Z",
      location: "Mesa de control administrativo",
      tags: ["seguro", "quirofano", "bloqueo"],
      requiresChecklist: true,
      checklistInstanceId: "h-chk-2",
      blockedReason: "Falta folio de aseguradora y validacion de cobertura",
    },
    {
      id: "h-tsk-3",
      title: "Seguimiento de alta a pacientes egresados del fin de semana",
      description: "Llamar a pacientes de egreso reciente para validar continuidad, receta, citas y signos de alerta.",
      priority: "high",
      columnId: "pending",
      assigneeId: "h-usr-operator-3",
      reporterId: "h-usr-supervisor-2",
      dueAt: "2026-03-16T18:30:00.000Z",
      createdAt: "2026-03-15T12:20:00.000Z",
      updatedAt: "2026-03-15T12:20:00.000Z",
      location: "Coordinacion de alta",
      tags: ["alta", "seguimiento", "egreso"],
      requiresChecklist: true,
      checklistInstanceId: "h-chk-3",
    },
    {
      id: "h-tsk-4",
      title: "Asignar cama para ingreso de trauma programado",
      description: "Coordinar cama, pase de enfermeria y documentos antes de las 11:00.",
      priority: "medium",
      columnId: "in_progress",
      assigneeId: "h-usr-operator-1",
      reporterId: "h-usr-supervisor-1",
      dueAt: "2026-03-16T17:00:00.000Z",
      createdAt: "2026-03-15T10:30:00.000Z",
      updatedAt: "2026-03-15T17:10:00.000Z",
      location: "Control de camas",
      tags: ["ingreso", "cama"],
      requiresChecklist: false,
    },
    {
      id: "h-tsk-5",
      title: "Cerrar incidente por demora en traslado interno",
      description: "Documentar causa, responsable, paciente afectado y accion correctiva del incidente.",
      priority: "critical",
      columnId: "pending",
      assigneeId: "h-usr-supervisor-2",
      reporterId: "h-usr-owner",
      dueAt: "2026-03-16T14:00:00.000Z",
      createdAt: "2026-03-15T11:40:00.000Z",
      updatedAt: "2026-03-15T11:40:00.000Z",
      location: "Centro de experiencia del paciente",
      tags: ["incidente", "traslado", "paciente"],
      requiresChecklist: false,
    },
    {
      id: "h-tsk-6",
      title: "Expediente clinico completo para resonancia con contraste",
      description: "Consentimiento, laboratorios y autorizacion listos para pasar a programacion.",
      priority: "high",
      columnId: "done",
      assigneeId: "h-usr-operator-2",
      reporterId: "h-usr-supervisor-1",
      dueAt: "2026-03-15T18:00:00.000Z",
      createdAt: "2026-03-14T16:00:00.000Z",
      updatedAt: "2026-03-15T17:50:00.000Z",
      completedAt: "2026-03-15T17:50:00.000Z",
      location: "Imagenologia",
      tags: ["expediente", "resonancia", "seguro"],
      requiresChecklist: true,
      checklistInstanceId: "h-chk-4",
    },
  ],
  checklists: [
    {
      id: "h-chk-1",
      taskId: "h-tsk-1",
      templateName: "Junta de admisiones",
      assigneeId: "h-usr-supervisor-1",
      status: "in_progress",
      items: [
        { id: "h-chk-1-1", label: "Consolidar ingresos del dia", done: true, required: true, completedAt: "2026-03-15T18:00:00.000Z" },
        { id: "h-chk-1-2", label: "Validar disponibilidad de camas", done: false, required: true },
        { id: "h-chk-1-3", label: "Listar autorizaciones pendientes", done: false, required: true },
      ],
    },
    {
      id: "h-chk-2",
      taskId: "h-tsk-2",
      templateName: "Autorizacion prequirurgica",
      assigneeId: "h-usr-operator-4",
      status: "pending",
      items: [
        { id: "h-chk-2-1", label: "Recibir folio de aseguradora", done: false, required: true },
        { id: "h-chk-2-2", label: "Confirmar cobertura y tabulador", done: false, required: true },
        { id: "h-chk-2-3", label: "Liberar pase a quirofano", done: false, required: true },
      ],
    },
    {
      id: "h-chk-3",
      taskId: "h-tsk-3",
      templateName: "Seguimiento post alta",
      assigneeId: "h-usr-operator-3",
      status: "pending",
      items: [
        { id: "h-chk-3-1", label: "Llamada realizada", done: false, required: true },
        { id: "h-chk-3-2", label: "Signos de alarma explicados", done: false, required: true },
        { id: "h-chk-3-3", label: "Cita de control confirmada", done: false, required: true },
      ],
    },
    {
      id: "h-chk-4",
      taskId: "h-tsk-6",
      templateName: "Expediente de estudio",
      assigneeId: "h-usr-operator-2",
      status: "complete",
      items: [
        { id: "h-chk-4-1", label: "Consentimiento firmado", done: true, required: true, completedAt: "2026-03-15T17:20:00.000Z" },
        { id: "h-chk-4-2", label: "Laboratorios cargados", done: true, required: true, completedAt: "2026-03-15T17:35:00.000Z" },
        { id: "h-chk-4-3", label: "Autorizacion confirmada", done: true, required: true, completedAt: "2026-03-15T17:48:00.000Z" },
      ],
    },
  ],
  alerts: [
    {
      id: "h-alt-1",
      title: "Autorizacion prequirurgica bloqueada",
      body: "El caso de laparoscopia sigue detenido por falta de folio y validacion de cobertura.",
      severity: "critical",
      read: false,
      createdAt: "2026-03-15T19:30:00.000Z",
      relatedTaskId: "h-tsk-2",
    },
    {
      id: "h-alt-2",
      title: "Altas sin seguimiento del fin de semana",
      body: "Hay pacientes egresados sin llamada de continuidad. Eso eleva riesgo de reingreso y mala experiencia.",
      severity: "warning",
      read: false,
      createdAt: "2026-03-15T20:00:00.000Z",
      relatedTaskId: "h-tsk-3",
    },
  ],
  activity: [
    { id: "h-act-1", actorId: "h-usr-supervisor-1", message: "Consolido agenda de ingresos y camas para la junta matutina", createdAt: "2026-03-15T18:05:00.000Z" },
    { id: "h-act-2", actorId: "h-usr-operator-2", message: "Completo expediente clinico para resonancia con contraste", createdAt: "2026-03-15T17:50:00.000Z" },
    { id: "h-act-3", actorId: "h-usr-owner", message: "Escalo incidente por demora en traslado interno", createdAt: "2026-03-15T18:45:00.000Z" },
  ],
  prospects: [
    {
      id: "h-prs-1",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      customerName: "Marta Cazares",
      salespersonId: "h-usr-operator-1",
      agency: "Hospital Santa Emilia Central",
      source: "Urgencias referida",
      status: "follow_up",
      createdAt: "2026-03-15T16:30:00.000Z",
      nextActionAt: "2026-03-16T15:30:00.000Z",
      vehicleInterest: "Ingreso por colecistectomia",
      financingRequired: true,
      notes: "Paciente con seguro activo. Falta confirmar folio y disponibilidad de quirofano.",
    },
    {
      id: "h-prs-2",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-norte",
      customerName: "Karla Nunez",
      salespersonId: "h-usr-operator-2",
      agency: "Hospital Santa Emilia Norte",
      source: "Consulta externa",
      status: "test_drive",
      createdAt: "2026-03-15T12:00:00.000Z",
      nextActionAt: "2026-03-16T17:00:00.000Z",
      vehicleInterest: "Resonancia con contraste",
      financingRequired: true,
      notes: "Ya acepto horario; solo falta confirmar preparacion y consentimiento.",
    },
    {
      id: "h-prs-3",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      customerName: "Luis Ortega",
      salespersonId: "h-usr-operator-1",
      agency: "Hospital Santa Emilia Central",
      source: "Traumatologia",
      status: "negotiation",
      createdAt: "2026-03-14T20:00:00.000Z",
      nextActionAt: "2026-03-16T14:30:00.000Z",
      vehicleInterest: "Cirugia de rodilla programada",
      financingRequired: true,
      notes: "Pendiente autorizacion final de aseguradora y asignacion de cama.",
    },
    {
      id: "h-prs-4",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      customerName: "Patricia Ramos",
      salespersonId: "h-usr-operator-3",
      agency: "Hospital Santa Emilia Central",
      source: "Piso de hospitalizacion",
      status: "closed_won",
      createdAt: "2026-03-13T18:00:00.000Z",
      vehicleInterest: "Egreso post parto",
      financingRequired: false,
      notes: "Paciente egresada, seguimiento de control en curso.",
    },
  ],
  testDrives: [
    {
      id: "h-td-1",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      prospectId: "h-prs-1",
      salespersonId: "h-usr-operator-1",
      agency: "Hospital Santa Emilia Central",
      vehicleModel: "Valoracion preoperatoria",
      scheduledAt: "2026-03-16T16:00:00.000Z",
      status: "scheduled",
    },
    {
      id: "h-td-2",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-norte",
      prospectId: "h-prs-2",
      salespersonId: "h-usr-operator-2",
      agency: "Hospital Santa Emilia Norte",
      vehicleModel: "Valoracion de imagenologia",
      scheduledAt: "2026-03-16T17:00:00.000Z",
      status: "scheduled",
    },
  ],
  salesOperations: [
    {
      id: "h-op-1",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      prospectId: "h-prs-1",
      customerName: "Marta Cazares",
      agency: "Hospital Santa Emilia Central",
      salespersonId: "h-usr-operator-1",
      vehicleModel: "Colecistectomia laparoscopica",
      stage: "negotiation",
      source: "Urgencias referida",
      financingRequired: true,
      financier: "Seguros Atlas",
      subsidyType: "insurance",
      subsidyAmount: 42000,
      tradeInRequired: false,
      closingProbability: 74,
      expectedCloseAt: "2026-03-17T17:00:00.000Z",
      nextStep: "Conseguir folio y confirmar hora de quirofano.",
      notes: "Caso caliente; riesgo por autorizacion.",
      createdAt: "2026-03-15T16:40:00.000Z",
      updatedAt: "2026-03-15T19:15:00.000Z",
    },
    {
      id: "h-op-2",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-norte",
      prospectId: "h-prs-2",
      customerName: "Karla Nunez",
      agency: "Hospital Santa Emilia Norte",
      salespersonId: "h-usr-operator-2",
      vehicleModel: "Resonancia con contraste",
      stage: "credit_review",
      source: "Consulta externa",
      financingRequired: true,
      financier: "GNP",
      subsidyType: "insurance",
      subsidyAmount: 12500,
      tradeInRequired: false,
      closingProbability: 86,
      expectedCloseAt: "2026-03-16T18:30:00.000Z",
      nextStep: "Recibir autorizacion digital y confirmar preparacion.",
      notes: "Expediente ordenado y paciente confirmada.",
      createdAt: "2026-03-15T12:10:00.000Z",
      updatedAt: "2026-03-15T18:20:00.000Z",
    },
    {
      id: "h-op-3",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      prospectId: "h-prs-3",
      customerName: "Luis Ortega",
      agency: "Hospital Santa Emilia Central",
      salespersonId: "h-usr-operator-1",
      vehicleModel: "Cirugia de rodilla",
      stage: "ready_to_close",
      source: "Traumatologia",
      financingRequired: true,
      financier: "MetLife",
      subsidyType: "insurance",
      subsidyAmount: 68000,
      tradeInRequired: false,
      closingProbability: 91,
      expectedCloseAt: "2026-03-16T15:30:00.000Z",
      nextStep: "Confirmar cama e ingresar documentos finales.",
      notes: "Depende de autorizacion final y logistica de cama.",
      createdAt: "2026-03-14T20:10:00.000Z",
      updatedAt: "2026-03-15T19:30:00.000Z",
    },
    {
      id: "h-op-4",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      prospectId: "h-prs-4",
      customerName: "Patricia Ramos",
      agency: "Hospital Santa Emilia Central",
      salespersonId: "h-usr-operator-3",
      vehicleModel: "Egreso post parto",
      stage: "closed_won",
      source: "Piso de hospitalizacion",
      financingRequired: false,
      financier: "Particular",
      subsidyType: "none",
      subsidyAmount: 0,
      tradeInRequired: false,
      closingProbability: 100,
      expectedCloseAt: "2026-03-13T20:00:00.000Z",
      nextStep: "Mantener seguimiento de signos de alarma y cita de control.",
      notes: "Caso cerrado con satisfaccion alta.",
      createdAt: "2026-03-13T18:05:00.000Z",
      updatedAt: "2026-03-13T20:15:00.000Z",
      closedAt: "2026-03-13T20:15:00.000Z",
    },
  ],
  creditFiles: [
    {
      id: "h-cf-1",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      operationId: "h-op-1",
      customerName: "Marta Cazares",
      agency: "Hospital Santa Emilia Central",
      salespersonId: "h-usr-operator-1",
      financier: "Seguros Atlas",
      status: "missing_documents",
      downPaymentReady: true,
      requiredDocuments: ["Poliza", "INE", "Orden medica", "Consentimiento informado"],
      receivedDocuments: ["Poliza", "INE"],
      missingDocuments: ["Orden medica", "Consentimiento informado"],
      notes: "Falta cerrar documentos para no perder ventana de quirofano.",
    },
    {
      id: "h-cf-2",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-norte",
      operationId: "h-op-2",
      customerName: "Karla Nunez",
      agency: "Hospital Santa Emilia Norte",
      salespersonId: "h-usr-operator-2",
      financier: "GNP",
      status: "submitted",
      downPaymentReady: true,
      requiredDocuments: ["Poliza", "INE", "Orden medica", "Consentimiento informado"],
      receivedDocuments: ["Poliza", "INE", "Orden medica", "Consentimiento informado"],
      missingDocuments: [],
      submittedAt: "2026-03-15T18:10:00.000Z",
      notes: "Esperando autorizacion final.",
    },
  ],
  bellIncidents: [
    {
      id: "h-inc-1",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      customerName: "Hector Mendoza",
      agency: "Hospital Santa Emilia Central",
      area: "service",
      severity: "critical",
      status: "open",
      summary: "Paciente reporta demora en traslado a estudios y falta de informacion al familiar.",
      ownerId: "h-usr-supervisor-2",
      createdAt: "2026-03-15T13:00:00.000Z",
      updatedAt: "2026-03-15T13:00:00.000Z",
    },
    {
      id: "h-inc-2",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-norte",
      customerName: "Rocio Bernal",
      agency: "Hospital Santa Emilia Norte",
      area: "admin",
      severity: "warning",
      status: "in_progress",
      summary: "Molestia por retraso en admision y validacion de cobertura.",
      ownerId: "h-usr-operator-4",
      createdAt: "2026-03-15T15:20:00.000Z",
      updatedAt: "2026-03-15T16:00:00.000Z",
    },
  ],
  postSaleFollowUps: [
    {
      id: "h-psf-1",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-central",
      customerName: "Patricia Ramos",
      vehicleModel: "Egreso post parto",
      salespersonId: "h-usr-operator-3",
      agency: "Hospital Santa Emilia Central",
      saleDate: "2026-03-13T20:15:00.000Z",
      dueAt: "2026-03-16T18:00:00.000Z",
      status: "pending",
      nextStep: "Llamar para validar sintomas, receta y cita de control.",
    },
    {
      id: "h-psf-2",
      groupId: "grp-santa-emilia",
      brandId: "brand-hospitales",
      siteId: "site-hospital-norte",
      customerName: "Daniela Flores",
      vehicleModel: "Egreso de cirugia ambulatoria",
      salespersonId: "h-usr-operator-2",
      agency: "Hospital Santa Emilia Norte",
      saleDate: "2026-03-12T17:00:00.000Z",
      dueAt: "2026-03-15T18:30:00.000Z",
      status: "at_risk",
      nextStep: "Recontactar hoy y confirmar evolucion con familiar.",
    },
  ],
  scheduledBroadcasts: [
    {
      id: "h-brd-1",
      title: "Convocatoria huddle clinico",
      message: "Capataz.ai: favor de reunirse en sala de comando para huddle de ingresos, camas e incidentes a las 7:15 a.m.",
      audience: "all_staff",
      frequency: "daily",
      timeOfDay: "07:15",
      timezone: "America/Mexico_City",
      active: true,
    },
    {
      id: "h-brd-2",
      title: "Corte de altas y autorizaciones",
      message: "Capataz.ai: enviar corte de altas, autorizaciones pendientes y camas por liberar antes de las 5:30 p.m.",
      audience: "sales_only",
      frequency: "weekdays",
      timeOfDay: "17:30",
      timezone: "America/Mexico_City",
      active: true,
    },
  ],
  scoreSnapshots: [
    { userId: "h-usr-supervisor-1", compliance: 92, speed: 87, consistency: 90, activity: 89, score: 90, trend: "up", note: "Mantiene admisiones y ocupacion bajo control visible." },
    { userId: "h-usr-operator-1", compliance: 66, speed: 70, consistency: 63, activity: 68, score: 67, trend: "steady", note: "Buen ritmo de ingresos, pero depende demasiado de autorizaciones externas." },
    { userId: "h-usr-operator-2", compliance: 88, speed: 86, consistency: 87, activity: 84, score: 86, trend: "up", note: "Ordena expedientes y programacion con muy buena disciplina." },
    { userId: "h-usr-supervisor-2", compliance: 74, speed: 72, consistency: 76, activity: 73, score: 74, trend: "steady", note: "Trae incidencias abiertas y presion de traslado interno." },
    { userId: "h-usr-operator-3", compliance: 85, speed: 81, consistency: 86, activity: 83, score: 84, trend: "up", note: "Seguimiento de alta bien documentado." },
    { userId: "h-usr-operator-4", compliance: 78, speed: 75, consistency: 77, activity: 76, score: 77, trend: "steady", note: "Mesa administrativa con presion alta por aseguradoras." },
  ],
  weekly: [
    { day: "Lun", completed: 9, alerts: 2, overdue: 1 },
    { day: "Mar", completed: 11, alerts: 1, overdue: 1 },
    { day: "Mie", completed: 8, alerts: 3, overdue: 2 },
    { day: "Jue", completed: 12, alerts: 2, overdue: 1 },
    { day: "Vie", completed: 10, alerts: 3, overdue: 2 },
    { day: "Sab", completed: 7, alerts: 2, overdue: 1 },
    { day: "Dom", completed: 6, alerts: 2, overdue: 1 },
  ],
  financeAccounts: [
    { id: "h-fa-1", userId: "h-usr-operator-1", kind: "wallet", label: "Saldo disponible", currency: "MXN", availableBalance: 4260, pendingBalance: 0, updatedAt: "2026-03-18T10:10:00.000Z" },
    { id: "h-fa-2", userId: "h-usr-operator-2", kind: "wallet", label: "Saldo disponible", currency: "MXN", availableBalance: 5890, pendingBalance: 0, updatedAt: "2026-03-18T10:10:00.000Z" },
  ],
  financeMovements: [
    { id: "h-fm-1", userId: "h-usr-operator-1", accountId: "h-fa-1", type: "payroll", status: "posted", title: "Nomina quincenal", detail: "Deposito de nomina", amount: 6900, createdAt: "2026-03-15T08:00:00.000Z" },
    { id: "h-fm-2", userId: "h-usr-operator-2", accountId: "h-fa-2", type: "payroll", status: "posted", title: "Nomina quincenal", detail: "Deposito de nomina", amount: 7420, createdAt: "2026-03-15T08:00:00.000Z" },
  ],
  financeApplications: [
    {
      id: "h-fapp-1",
      userId: "h-usr-operator-2",
      productId: "salary_advance",
      productName: "Adelanto de nomina",
      requestedAmount: 3000,
      status: "approved",
      requestedAt: "2026-03-16T11:30:00.000Z",
      updatedAt: "2026-03-16T13:00:00.000Z",
      paymentPerPeriod: 3000,
      termLabel: "Quincena",
      rationale: "Apoyo para traslado familiar",
      aiSummary: "Aprobacion demo por score alto y continuidad operativa estable.",
    },
  ],
  financeInsights: [
    { id: "h-fi-1", title: "Beneficios hospitalarios activos", body: "La red ya puede mostrar la capa de beneficios y adelanto salarial sobre el mismo runtime operativo.", tone: "positive", createdAt: "2026-03-18T09:00:00.000Z" },
  ],
};
